# Generated by Django 2.0.4 on 2018-06-12 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPlatform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='identity',
            new_name='iden',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='password',
            new_name='psd',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='user',
        ),
    ]
