# Generated by Django 2.0.4 on 2018-06-12 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('WebPlatform', '0002_auto_20180612_2208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='iden',
            new_name='identity',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='psd',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user',
            new_name='username',
        ),
    ]
