# Generated by Django 2.0.4 on 2018-06-14 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPlatform', '0003_auto_20180612_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='interval',
            field=models.CharField(max_length=13),
        ),
    ]
