# Generated by Django 2.0.4 on 2018-06-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPlatform', '0004_auto_20180614_2103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='address',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='oder',
            name='date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='oder',
            name='interval',
            field=models.CharField(max_length=50),
        ),
    ]
