# Generated by Django 2.0.4 on 2018-06-14 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPlatform', '0005_auto_20180614_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='allocation',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oder',
            name='amount',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oder',
            name='complete',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='oder',
            name='oderNumber',
            field=models.CharField(max_length=20),
        ),
    ]
