# Generated by Django 2.0.4 on 2018-06-14 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPlatform', '0006_auto_20180614_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oder',
            name='allocation',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oder',
            name='amount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oder',
            name='complete',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='oder',
            name='oderNumber',
            field=models.IntegerField(),
        ),
    ]
