# Generated by Django 2.0.4 on 2018-06-21 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('WebPlatform', '0007_auto_20180614_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oderNumber', models.IntegerField()),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=500)),
            ],
        ),
    ]
